-- CreateTable
CREATE TABLE "ValorOne" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "numberone" INTEGER NOT NULL
);

-- CreateTable
CREATE TABLE "ValorTwo" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "numbertwo" INTEGER NOT NULL
);

-- CreateTable
CREATE TABLE "Resultado" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "resultado" INTEGER NOT NULL
);
